name: flutter_painter_v2
version: 2.1.0+1
description: A Flutter widget to draw scribbles, text, shapes and images on a background image or color
homepage: https://github.com/hatemragab/flutter_painter_v2
repository: https://github.com/hatemragab/flutter_painter_v2
issue_tracker: https://github.com/hatemragab/flutter_painter_v2/issues

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.18.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
